- name: variables set
  set_fact:
    wp_domain: "{{ wordpress_settings.domain }}"
    wp_dir: "{{ wordpress_settings.directory }}"
    wp_db_host: "{{ wordpress_settings.dbnode }}"
    wp_db_name: "{{ wordpress_settings.database }}"
    wp_db_user: "{{ wordpress_settings.user }}"
    wp_db_pwd: "{{ wordpress_settings.password }}"
    wp_admin_pwd: "{{ wordpress_settings.admin_password }}"
  no_log: True
- name: wordpress database(s) present
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_host: "{{ wp_db_host }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: True
  when: not import_databases
- block:
  - name: database dump file copied
    copy:
      src: "{{ dump_file }}"
      dest: /tmp
    register: copy_result
  - name: database restored
    mysql_db:
      name: "{{ wp_db_name }}"
      state: import
      target: "{{ copy_result.path }}"
      login_host: "{{ wp_db_host }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
  no_log: True
  when: import_databases
- name: db user created
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pwd }}"
    state: present
    host: "%"
    priv: "{{ wp_db_name }}.*:ALL"
    login_host: "{{ wp_db_host }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: True
- name: wordpress target directory /var/www/{{ wp_dir }} available
  file:
    path: "/var/www/{{ wp_dir }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rx"
    owner: nginx
    group: nginx
- name: robots.txt present on test
  copy:
    src: robots.txt
    dest: "/var/www/{{ wp_dir }}/robots.txt"
    owner: root
    group: root
    mode: 0644
  when: install_test_site

- name: set selinux policies
  sefcontext:
    target: '/var/www/{{ wp_dir }}(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  notify: restorecon
- name: latest wordpress version downloaded
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "/tmp/{{ wp_dir }}-latest.tar.gz"
    mode: 0644
    force: yes
  check_mode: no
  register: wordpress_download
- name: unpack wordpress to /var/www/{{ wp_dir }}
  unarchive:
    src: "/tmp/{{ wp_dir }}-latest.tar.gz"
    dest: /var/www/{{ wp_dir }}/
    owner: nginx
    group: nginx
    extra_opts: "--strip-components=1"
    remote_src: yes
- name: configured /var/www/{{ wp_dir }}/wp-config.php
  template:
    src: templates/wp-config.php.j2
    dest: /var/www/{{ wp_dir }}/wp-config.php
    owner: root
    group: nginx
    mode: 0640
- name: wordpress configured
  shell: "wp core install --url={{ wp_domain }} --title={{ wp_dir }} --admin_user=admin --admin_password={{ wp_admin_pwd }} --skip-email --path=/var/www/{{ wp_dir }} --admin_email=noop@noop.com"
  no_log: True
  args:
    warn: False
- name: themes installed
  ansible_wp:
    path: "/var/www/{{ wp_dir }}"
    state: latest
    theme: "{{ wordpress_settings.theme }}"
  tags: themes
- name: proper permissions set on themes
  file:
    path: "/var/www/{{ wp_dir }}/wp-content/themes/{{ wordpress_settings.theme }}"
    owner: nginx
    group: nginx
    recurse: yes
  tags: themes
- name: plugins installed
  ansible_wp:
    path: "/var/www/{{ wp_dir }}"
    state: latest
    plugin: "{{ wordpress_settings.plugin}}"
- name: proper permissions set on plugins
  file:
    path: "/var/www/{{ wp_dir }}/wp-content/plugins/{{ wordpress_settings.plugin }}"
    owner: nginx
    group: nginx
    recurse: yes
- name: OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "/etc/pki/tls/private/{{ wp_domain }}.key"
- name: Diffie-Hellman parameters
  community.crypto.openssl_dhparam:
    path: /etc/pki/tls/certs/dhparams.pem
- name: self signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "/etc/pki/tls/certs/{{ wp_domain }}.crt"
    privatekey_path: "/etc/pki/tls/private/{{ wp_domain }}.key"
    provider: selfsigned
- name: latest nginx ssl conf
  template:
    src: templates/nginx.ssl.conf.j2
    dest: "/etc/nginx/conf.d/{{ wp_domain }}.ssl.conf"
  notify: restart nginx
