- name: variables set
  set_fact:
    wp_domain: "{{ wordpress_settings.domain }}"
    wp_dir: "{{ wordpress_settings.directory }}"
    wp_db_host: "{{ wordpress_settings.dbnode }}"
    wp_db_name: "{{ wordpress_settings.database }}"
    wp_db_user: "{{ wordpress_settings.user }}"
    wp_db_pwd: "{{ wordpress_settings.password }}"
- name: db user created
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pwd }}"
    state: present
    host: "%"
    priv: "{{ wp_db_name }}.*:ALL"
    login_host: "{{ wp_db_host }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
- block:
  - name: database dump file copied
    copy:
      src: "{{ dump_file }}"
      dest: /tmp
  - name: database restored
    mysql_db:
      name: "{{ wp_db_name }}"
      state: import
      target: "/tmp/{{ dump_file }}"
      login_host: "{{ wp_db_host }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
  when: import_databases
- name: wordpress target directory /var/www/{{ wp_dir }} available
  file:
    path: "/var/www/{{ wp_dir }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rx"
    owner: nginx
    group: nginx
- name: set selinux policies
  sefcontext:
    target: '/var/www/{{ wp_dir }}(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  notify: restorecon
- name: latest wordpress version downloaded
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "/tmp/{{ wp_dir }}-latest.tar.gz"
    mode: 0644
    force: yes
  check_mode: no
  register: wordpress_download
- name: unpack wordpress to /var/www/{{ wp_dir }}
  unarchive:
    src: "/tmp/{{ wp_dir }}-latest.tar.gz"
    dest: /var/www/{{ wp_dir }}/
    owner: nginx
    group: nginx
    extra_opts: "--strip-components=1"
    remote_src: yes
- name: configured /var/www/{{ wp_dir }}/wp-config.php
  template:
    src: templates/wp-config.php.j2
    dest: /var/www/{{ wp_dir }}/wp-config.php
    owner: nginx
    group: nginx
    mode: 0640
- name: themes installed
  ansible_wp:
    path: "/var/www/{{ wp_dir }}"
    state: latest
    theme: "{{ wordpress_settings.theme }}"
  tags: themes
- name: proper permissions set on themes
  file:
    path: "/var/www/{{ wp_dir }}/wp-content/themes/{{ wordpress_settings.theme }}"
    owner: nginx
    group: nginx
    recurse: yes
  tags: themes
- name: plugins installed
  ansible_wp:
    path: "/var/www/{{ wp_dir }}"
    state: latest
    plugin: "{{ wordpress_settings.plugin}}"
- name: proper permissions set on plugins
  file:
    path: "/var/www/{{ wp_dir }}/wp-content/plugins/{{ wordpress_settings.plugin }}"
    owner: nginx
    group: nginx
    recurse: yes

#- name: get latest yoastseo version
#  local_action: latest_yoastseo_version
#  register: result_latest
#- name: set version variable
#  set_fact:
#    yoastseo_version: "{{ result_latest.msg }}"
#- name: download latest yoastseo theme
#  get_url:
#    url: "https://downloads.wordpress.org/plugin/wordpress-seo.{{ yoastseo_version }}.zip"
#    dest: "/tmp/{{ wp_dir }}-wordpress-seo.{{ yoastseo_version }}.zip"
#    force: no
#  register: result_get
#- name: unpack plugins
#  unarchive:
#    src: "/tmp/{{ wp_dir }}-wordpress-seo.{{ yoastseo_version }}.zip"
#    dest: "/var/www/{{ wp_dir }}/wp-content/plugins"
#    owner: nginx
#    group: nginx
#    remote_src: yes
 
