- name: wp-cli link set
  file:
    src: "{{ wp_cli_path }}/{{ wp_cli_bin }}"
    dest: "{{ wp_cli_path }}/{{ wp_cli_exe }}"
    state: link
- block:
  - name: test deployed
    set_fact:
      wordpress_settings: "{{ wordpress_test_settings }}"
  - import_tasks: enforce_wordpress.yml
  when: install_test_site
- block:
  - name: prod deployed
    set_fact:
      wordpress_settings: "{{ wordpress_prod_settings }}"
  - import_tasks: enforce_wordpress.yml
  when: install_prod_site
